spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:http://localhost:9094}
    consumer:
      group-id: notifications-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: shared.dto.NotificationEvent
        spring.json.use.type.headers: false
        isolation.level: read_committed
        max.poll.records: 10
      listener:
        ack-mode: manual_immediate
        concurrency: 3

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bank}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8080/realms/bank/protocol/openid-connect/certs}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVICE_URL:http://localhost:9411/api/v2/spans} # Эндпоинт Zipkin для приёма спанов
  tracing:
    sampling:
      probability: 1 # Сэмплируем все запросы

logging:
  level:
    org.springframework.kafka: INFO
    com.example.notification: ${LOGGING_LEVEL_APP:DEBUG}
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

server:
  port: ${SERVER_PORT:8085}
