plugins {
    id 'org.springframework.boot' version '3.5.7'
    id 'io.spring.dependency-management' version '1.1.7'
}

allprojects {
    group = 'microservices-platform'
    version = '1.0.0'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'

    java {
        sourceCompatibility = JavaVersion.VERSION_21
    }

//    dependencyManagement {
//        imports {
//            // Измените версию на совместимую с Spring Boot 3.5.x
////            mavenBom "org.springframework.cloud:spring-cloud-dependencies:2025.0.0"
//        }
//    }

    dependencies {
        compileOnly 'org.projectlombok:lombok'
        annotationProcessor 'org.projectlombok:lombok'
        implementation 'net.logstash.logback:logstash-logback-encoder:8.0'
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
    }

    test {
        useJUnitPlatform()
    }
}