version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.1
    container_name: mb-keycloak
    command: [ "start-dev", "--import-realm", "--http-port=8080", "--http-enabled=true" ]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
      KC_HOSTNAME: "http://localhost:8080"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
        - ./keycloak/bank-realm.json:/opt/keycloak/data/import/bank-realm.json:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 40s

  db:
    image: postgres:17
    container_name: database
    networks:
      - bank-network
    environment:
      - POSTGRES_DB=${DB_POSTGRES_NAME}
      - POSTGRES_USER=${DB_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_bank_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_POSTGRES_USERNAME} -d ${DB_POSTGRES_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 10

  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT  # ДОБАВЛЕНО PLAINTEXT_HOST
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    networks:
      - bank-network
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "kafka:9092", "--list" ]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
       - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    ports:
      - "8081:8080"
    networks:
       - bank-network
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # Открываем порт для доступа к веб-интерфейсу
    volumes:
      - ./prometheus-data:/metrics/prometheus  # Папка для хранения данных
      - ./metrics/prometheus:/etc/prometheus:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=90d'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - bank-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Веб-интерфейс Grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=false  # Отключаем анонимный доступ
    volumes:
      - ./grafana-data:/var/lib/grafana  # Данные Grafana (дашборды, настройки)
      - ./metrics/grafana:/etc/grafana/provisioning:ro  # Автоматическая настройка datasource
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - bank-network

networks:
  bank-network:
  kafka-network:

volumes:
  keycloak_data:
  postgres_bank_data: