version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "${KEYCLOAK_PORT}:8080"
    networks:
      - bank-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  db:
    image: postgres:17
    container_name: database
    networks:
      - bank-network
    environment:
      - POSTGRES_DB=${DB_POSTGRES_NAME}
      - POSTGRES_USER=${DB_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${DB_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_bank_data:/var/lib/postgresql/data


networks:
  bank-network:

volumes:
  keycloak_data:
  postgres_bank_data: