spring:
  datasource:
    url: ${DB_POSTGRES_URI:jdbc:postgresql://localhost:5432/bank}
    username: ${DB_POSTGRES_USERNAME:bank}
    password: ${DB_POSTGRES_PASSWORD:bank}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      client:
        registration:
          # ????????? Keycloak
          keycloak:
            provider: keycloak
            client-id: ${CASH_KEYCLOAK_CLIENT_ID:cash-service}
            client-secret: ${CASH_KEYCLOAK_CLIENT_SECRET:qSSVfNLbFKkmlvIN2rcuw23umfMd2y5d}
            authorization-grant-type: client_credentials
            scope:
              - openid
              - profile
              - email

        provider:
          # ????????? ??? Keycloak
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bank}
            # ?????????????? ????????? ????? endpoints
            authorization-uri: ${KEYCLOAK_AUTH_URI:http://localhost:8080/realms/bank/protocol/openid-connect/auth}
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8080/realms/bank/protocol/openid-connect/token}
            user-info-uri: ${KEYCLOAK_USERINFO_URI:http://localhost:8080/realms/bank/protocol/openid-connect/userinfo}
            jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8080/realms/bank/protocol/openid-connect/certs}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bank}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8080/realms/bank/protocol/openid-connect/certs}
server:
  port: 3002
management:
  endpoints:
    web:
      exposure:
        include: refresh

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
  instance:
    prefer-ip-address: true

services:
  accounts:
    url: ${ACCOUNTS_SERVICE_URL:http://localhost:3000}
  notification:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:3003}