server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: accounts-route
              uri: lb://accounts-service
              predicates:
                - Path=/api/accounts/**
              filters:
                - StripPrefix=1

            - id: transfer-route
              uri: lb://transfer-service
              predicates:
                - Path=/api/transfer/**
              filters:
                - StripPrefix=1

            - id: cash-route
              uri: lb://cash-service
              predicates:
                - Path=/api/cash/**
              filters:
                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG