spring:
  application:
    name: front
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID:front}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:DG5Ve2hCLrGsOMUG0G5v9Yc7OgACOpCw}
            authorization-grant-type: authorization_code
            redirect-uri: ${KEYCLOAK_REDIRECT_URI:http://localhost:8000/login/oauth2/code/keycloak}
            scope:
              - openid
              - profile
              - email

        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bank}
            user-name-attribute: preferred_username
  management:
    endpoints:
      web:
        exposure:
          include: health,info
    endpoint:
      health:
        show-details: always

server:
  port: 8080

services:
  gateway:
    url: ${GATEWAY_SERVICE_URL:http://localhost:8001}

# Для отладки
logging:
  level:
    org.springframework.cloud.config.client: DEBUG
    org.springframework.web: DEBUG