spring:
  application:
    name: my-bank-front-app
  security:
    oauth2:
      client:
        registration:
          # ????????? Keycloak
          keycloak:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID:front}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:DG5Ve2hCLrGsOMUG0G5v9Yc7OgACOpCw}
            authorization-grant-type: authorization_code
            redirect-uri: ${KEYCLOAK_REDIRECT_URI:http://localhost:8000/login/oauth2/code/keycloak}
            scope:
              - openid
              - profile
              - email

        provider:
          # ????????? ??? Keycloak
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9000/realms/bank}
            # ?????????????? ????????? ????? endpoints
            authorization-uri: ${KEYCLOAK_AUTH_URI:http://localhost:9000/realms/bank/protocol/openid-connect/auth}
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:9000/realms/bank/protocol/openid-connect/token}
            user-info-uri: ${KEYCLOAK_USERINFO_URI:http://localhost:9000/realms/bank/protocol/openid-connect/userinfo}
            jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:9000/realms/bank/protocol/openid-connect/certs}
            user-name-attribute: preferred_username
server:
  port: 8000

services:
  gateway:
    url: http://localhost:8080