spring:
  application:
    name: front
  config:
    import: configserver:http://localhost:8088

# Для отладки
logging:
  level:
    org.springframework.cloud.config.client: DEBUG
    org.springframework.web: DEBUG