spring:
  application:
    name: transfer-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:http://localhost:9094}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: ${TRANSFER_KEYCLOAK_CLIENT_ID:transfer-service}
            client-secret: ${TRANSFER_KEYCLOAK_CLIENT_SECRET:NrIrH223UNvtiqcIdmVwSsczXzOpa5PB}
            authorization-grant-type: client_credentials
            scope:
              - openid
              - profile
              - email

        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bank}
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bank}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8080/realms/bank/protocol/openid-connect/certs}
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

server:
  port: ${SERVER_PORT:8084}

services:
  accounts:
    url: ${ACCOUNTS_SERVICE_URL:http://localhost:8082}

kafka:
  topic:
    notification:
      name: "notification-topic"

# Для отладки
logging:
  level:
    org.springframework.cloud.config.client: DEBUG
    org.springframework.web: DEBUG