replicas: 1
port: 8080

image:
  repository: bank/front
  tag: "1.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080


config:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8080"

  KEYCLOAK_ISSUER_URI: "http://auth.bank.local/realms/bank"
  KEYCLOAK_CLIENT_ID: "front"
  KEYCLOAK_REDIRECT_URI: "http://bank.local/login/oauth2/code/keycloak"


  GATEWAY_SERVICE_URL: "http://bank.local"

secrets:
  KEYCLOAK_CLIENT_SECRET: "DG5Ve2hCLrGsOMUG0G5v9Yc7OgACOpCw"

resources: {}

global:
  imagePullPolicy: IfNotPresent
  hostAliases: []

waitForOidc: "http://auth.bank.local/realms/bank/.well-known/openid-configuration"