spring:
  application:
    name: accounts-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:http://localhost:9094}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/bank}

  datasource:
    url: ${DB_POSTGRES_URI:jdbc:postgresql://localhost:5432/bank?currentSchema=bank_accounts}
    username: ${DB_POSTGRES_USERNAME:bank}
    password: ${DB_POSTGRES_PASSWORD:bank}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: bank_accounts

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: bank_accounts

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: bank_accounts

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVICE_URL:http://localhost:9411/api/v2/spans} # Эндпоинт Zipkin для приёма спанов
  tracing:
    sampling:
      probability: 1.0 # Сэмплируем все запросы

server:
  port: ${SERVER_PORT:8082}

kafka:
  topic:
    notification:
      name: "notification-topic"

logging:
  level:
    com.example.accounts: ${LOGGING_LEVEL_APP:DEBUG}
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"