replicas: 1
port: 8080

image:
  repository: bank/notifications-service
  tag: "1.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

config:
  SPRING_PROFILES_ACTIVE: "k8s"
  SERVER_PORT: "8080"
  KEYCLOAK_ISSUER_URI: "http://auth.bank.local/realms/bank"
  KEYCLOAK_JWK_URI: "http://auth.bank.local/realms/bank/protocol/openid-connect/certs"


secrets:
  PLACEHOLDER: "unused"

resources: {}

global:
  imagePullPolicy: IfNotPresent
  hostAliases: []
