plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.7'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'org.springframework.cloud.contract' version "4.3.0"
	id 'maven-publish'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
	maven { url = 'https://repo.spring.io/snapshot' }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.liquibase:liquibase-core'
	implementation 'org.springframework.kafka:spring-kafka'
	implementation(project(":shared"))
	runtimeOnly 'org.postgresql:postgresql'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}


contractTest {
	useJUnitPlatform()
	jvmArgs "-javaagent:${classpath.find { it.name.contains('byte-buddy-agent') }.absolutePath}"
}

contracts {
	// Базовый класс для тестов
	baseClassForTests = 'com.example.accounts.BaseAccountContractsTest'
	failOnNoContracts = false

	// Указываем, где лежат контракты
	contractsDslDir = file("src/test/resources/contract")
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			groupId = 'com.example'
			artifactId = 'accounts'
			version = '0.0.1-SNAPSHOT'

			// Публикация основного JAR
			from components.java

			// Публикация JAR со стэбами
			artifact verifierStubsJar
		}
	}
}